create table if not exists newsletter (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table newsletter enable row level security;

create policy "Anyone can subscribe" on newsletter for insert with check (true);
